services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/12345678  # Change 'yourpassword' to your desired password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]  # Added GDS library
    volumes:
      # - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  # neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
